/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author paulp
 */
public class MusicGUI extends javax.swing.JFrame {
    public ArrayList<Song> songs;
    public ArrayList<String> likedSongs;
    public ArrayList<String> aSongs;
    public ArrayList<String> bSongs;
    
    StackInterface SI;
    /**
     * Creates new form MusicGUI
     */
    public MusicGUI() {
        initComponents();
        songs = new ArrayList<>();
        likedSongs = new ArrayList<>();
        aSongs = new ArrayList<>();
        bSongs = new ArrayList<>();
        SI = new LikedPlaylist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreGroup = new javax.swing.ButtonGroup();
        navBar = new javax.swing.JPanel();
        musicLbl = new javax.swing.JLabel();
        likedTab = new javax.swing.JPanel();
        likedTabBtn = new javax.swing.JButton();
        indieTab = new javax.swing.JPanel();
        indieTabBtn = new javax.swing.JButton();
        rockTab = new javax.swing.JPanel();
        rockTabBtn = new javax.swing.JButton();
        repeatTab = new javax.swing.JPanel();
        repeatTabBtn = new javax.swing.JButton();
        exit = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        playlistContainer = new javax.swing.JPanel();
        likedPage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        likedTA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        songTxtField = new javax.swing.JTextField();
        indieRbtn = new javax.swing.JRadioButton();
        rockRBtn = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        countLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        indiePage = new javax.swing.JPanel();
        iSearchBtn = new javax.swing.JButton();
        iCountLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        indieTA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        iDeleteBtn = new javax.swing.JButton();
        iClearBtn = new javax.swing.JButton();
        iSongTxtField = new javax.swing.JTextField();
        rockPage = new javax.swing.JPanel();
        iDeleteBtn1 = new javax.swing.JButton();
        iClearBtn1 = new javax.swing.JButton();
        iSongTxtField1 = new javax.swing.JTextField();
        iSearchBtn1 = new javax.swing.JButton();
        iCountLbl1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        indieTA1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        repeatPage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navBar.setBackground(new java.awt.Color(204, 153, 255));

        musicLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        musicLbl.setText("MUSIC PLAYLIST MANAGER");

        likedTabBtn.setBackground(new java.awt.Color(255, 204, 255));
        likedTabBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        likedTabBtn.setText("Liked");
        likedTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout likedTabLayout = new javax.swing.GroupLayout(likedTab);
        likedTab.setLayout(likedTabLayout);
        likedTabLayout.setHorizontalGroup(
            likedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(likedTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        likedTabLayout.setVerticalGroup(
            likedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(likedTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        indieTabBtn.setBackground(new java.awt.Color(255, 204, 255));
        indieTabBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        indieTabBtn.setText("Indie");
        indieTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indieTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indieTabLayout = new javax.swing.GroupLayout(indieTab);
        indieTab.setLayout(indieTabLayout);
        indieTabLayout.setHorizontalGroup(
            indieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indieTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        indieTabLayout.setVerticalGroup(
            indieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indieTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rockTabBtn.setBackground(new java.awt.Color(255, 204, 255));
        rockTabBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rockTabBtn.setText("Rock");
        rockTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rockTabLayout = new javax.swing.GroupLayout(rockTab);
        rockTab.setLayout(rockTabLayout);
        rockTabLayout.setHorizontalGroup(
            rockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rockTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        rockTabLayout.setVerticalGroup(
            rockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rockTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        repeatTabBtn.setBackground(new java.awt.Color(255, 204, 255));
        repeatTabBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        repeatTabBtn.setText("Repeat");
        repeatTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout repeatTabLayout = new javax.swing.GroupLayout(repeatTab);
        repeatTab.setLayout(repeatTabLayout);
        repeatTabLayout.setHorizontalGroup(
            repeatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(repeatTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        repeatTabLayout.setVerticalGroup(
            repeatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(repeatTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        exitBtn.setBackground(new java.awt.Color(255, 204, 255));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitBtn.setText("X");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(navBarLayout.createSequentialGroup()
                        .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(navBarLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(likedTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(indieTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rockTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(repeatTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(navBarLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(musicLbl))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(musicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(likedTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indieTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rockTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(repeatTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        playlistContainer.setBackground(new java.awt.Color(204, 204, 204));
        playlistContainer.setLayout(new java.awt.CardLayout());

        likedPage.setBackground(new java.awt.Color(204, 153, 255));
        likedPage.setPreferredSize(new java.awt.Dimension(529, 355));

        likedTA.setColumns(20);
        likedTA.setRows(5);
        jScrollPane1.setViewportView(likedTA);

        jButton1.setText("Add to");

        genreGroup.add(indieRbtn);
        indieRbtn.setText("Indie");

        genreGroup.add(rockRBtn);
        rockRBtn.setText("Rock");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        countLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLbl.setText("There are 0 songs in your playlist");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Liked Playlist");

        deleteBtn.setText("Remove");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout likedPageLayout = new javax.swing.GroupLayout(likedPage);
        likedPage.setLayout(likedPageLayout);
        likedPageLayout.setHorizontalGroup(
            likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likedPageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(likedPageLayout.createSequentialGroup()
                        .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(likedPageLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn))
                            .addComponent(countLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(likedPageLayout.createSequentialGroup()
                                .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(songTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(indieRbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rockRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(likedPageLayout.createSequentialGroup()
                        .addComponent(deleteBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, likedPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addContainerGap())
        );
        likedPageLayout.setVerticalGroup(
            likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likedPageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(likedPageLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(songTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn)
                            .addComponent(searchBtn))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(indieRbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rockRBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn)
                        .addGap(12, 12, 12)
                        .addComponent(countLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addContainerGap())
        );

        playlistContainer.add(likedPage, "card2");

        indiePage.setBackground(new java.awt.Color(204, 153, 255));

        iSearchBtn.setText("Search");
        iSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSearchBtnActionPerformed(evt);
            }
        });

        iCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iCountLbl.setText("There are 0 songs in your playlist");

        indieTA.setColumns(20);
        indieTA.setRows(5);
        jScrollPane2.setViewportView(indieTA);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Indie Playlist");

        iDeleteBtn.setText("Remove");
        iDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iDeleteBtnActionPerformed(evt);
            }
        });

        iClearBtn.setText("Clear");
        iClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indiePageLayout = new javax.swing.GroupLayout(indiePage);
        indiePage.setLayout(indiePageLayout);
        indiePageLayout.setHorizontalGroup(
            indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiePageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indiePageLayout.createSequentialGroup()
                        .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(indiePageLayout.createSequentialGroup()
                                .addComponent(iSongTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iSearchBtn)))
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(iCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(indiePageLayout.createSequentialGroup()
                        .addComponent(iDeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iClearBtn)))
                .addContainerGap())
        );
        indiePageLayout.setVerticalGroup(
            indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiePageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(indiePageLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iSongTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iSearchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iDeleteBtn)
                            .addComponent(iClearBtn))
                        .addGap(12, 12, 12)
                        .addComponent(iCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        playlistContainer.add(indiePage, "card3");

        rockPage.setBackground(new java.awt.Color(204, 153, 255));

        iDeleteBtn1.setText("Remove");
        iDeleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iDeleteBtn1ActionPerformed(evt);
            }
        });

        iClearBtn1.setText("Clear");
        iClearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iClearBtn1ActionPerformed(evt);
            }
        });

        iSearchBtn1.setText("Search");
        iSearchBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSearchBtn1ActionPerformed(evt);
            }
        });

        iCountLbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iCountLbl1.setText("There are 0 songs in your playlist");

        indieTA1.setColumns(20);
        indieTA1.setRows(5);
        jScrollPane3.setViewportView(indieTA1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Indie Playlist");

        javax.swing.GroupLayout rockPageLayout = new javax.swing.GroupLayout(rockPage);
        rockPage.setLayout(rockPageLayout);
        rockPageLayout.setHorizontalGroup(
            rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockPageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rockPageLayout.createSequentialGroup()
                        .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rockPageLayout.createSequentialGroup()
                                .addComponent(iSongTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iSearchBtn1)))
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(iCountLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rockPageLayout.createSequentialGroup()
                        .addComponent(iDeleteBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iClearBtn1)))
                .addContainerGap())
        );
        rockPageLayout.setVerticalGroup(
            rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockPageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rockPageLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iSongTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iSearchBtn1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iDeleteBtn1)
                            .addComponent(iClearBtn1))
                        .addGap(12, 12, 12)
                        .addComponent(iCountLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        playlistContainer.add(rockPage, "card4");

        repeatPage.setBackground(new java.awt.Color(204, 153, 255));
        repeatPage.setPreferredSize(new java.awt.Dimension(515, 379));

        javax.swing.GroupLayout repeatPageLayout = new javax.swing.GroupLayout(repeatPage);
        repeatPage.setLayout(repeatPageLayout);
        repeatPageLayout.setHorizontalGroup(
            repeatPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        repeatPageLayout.setVerticalGroup(
            repeatPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        playlistContainer.add(repeatPage, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playlistContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playlistContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void likedTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedTabBtnActionPerformed
        // TODO add your handling code here:
        likedPage.setVisible(true);
        indiePage.setVisible(false);
        rockPage.setVisible(false);
        repeatPage.setVisible(false);

    }//GEN-LAST:event_likedTabBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void indieTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indieTabBtnActionPerformed
        // TODO add your handling code here:
        likedPage.setVisible(false);
        indiePage.setVisible(true);
        rockPage.setVisible(false);
        repeatPage.setVisible(false);
        
    }//GEN-LAST:event_indieTabBtnActionPerformed

    private void rockTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockTabBtnActionPerformed
        // TODO add your handling code here:
        likedPage.setVisible(false);
        indiePage.setVisible(false);
        rockPage.setVisible(true);
        repeatPage.setVisible(false);
        
    }//GEN-LAST:event_rockTabBtnActionPerformed

    private void repeatTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatTabBtnActionPerformed
        // TODO add your handling code here:
        likedPage.setVisible(false);
        indiePage.setVisible(false);
        rockPage.setVisible(false);
        repeatPage.setVisible(true);        
    }//GEN-LAST:event_repeatTabBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        //associate title with textfield
        String title = songTxtField.getText();
        
        /*
        //create new title within Song class
        Song song = new Song(title);
        //create Playlist class
        Playlist playlist = new Playlist();
        //add title of song into Playlist ArrayList
        playlist.add(song);
        
        ///retrieve
        ArrayList<Song> songs = playlist.getSongs();

        if (songs.isEmpty()) {
            likedTA.setText("Nothing in your playlist!");
        } else {
            // Iterate over the songs and display their titles
            for (Song s : songs) {
                likedTA.append(s.getTitle() + "\n");
            }
        }
        */
        
        //stack
        SI.push(title);
        //likedTA.append(title + "\n");
        likedTA.setText("");
        likedTA.append(SI.displayStack() + "\n");
        int songNum = SI.size();
        countLbl.setText("There are " + songNum + " songs in your playlist\n");
        songTxtField.setText("");

    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        // Get the target element to search for
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String title = songTxtField.getText();

        if (SI.isEmpty()) {
            likedTA.append("There are no songs to be removed\n");
        } else {
            SI.pop();
            likedTA.setText("");
            likedTA.append(SI.displayStack() + "\n");
            int songNum = SI.size();
            countLbl.setText("There are " + songNum + " songs in your playlist\n");
        }


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
            SI.emptyStack();
            int songNum = SI.size();
            countLbl.setText("There are " + songNum + " songs in your playlist\n");
            likedTA.setText("");
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void iSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iSearchBtnActionPerformed

    private void iClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iClearBtnActionPerformed

    private void iDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iDeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iDeleteBtnActionPerformed

    private void iDeleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iDeleteBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iDeleteBtn1ActionPerformed

    private void iClearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iClearBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iClearBtn1ActionPerformed

    private void iSearchBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSearchBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iSearchBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel countLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel exit;
    private javax.swing.JButton exitBtn;
    private javax.swing.ButtonGroup genreGroup;
    private javax.swing.JButton iClearBtn;
    private javax.swing.JButton iClearBtn1;
    private javax.swing.JLabel iCountLbl;
    private javax.swing.JLabel iCountLbl1;
    private javax.swing.JButton iDeleteBtn;
    private javax.swing.JButton iDeleteBtn1;
    private javax.swing.JButton iSearchBtn;
    private javax.swing.JButton iSearchBtn1;
    private javax.swing.JTextField iSongTxtField;
    private javax.swing.JTextField iSongTxtField1;
    private javax.swing.JPanel indiePage;
    private javax.swing.JRadioButton indieRbtn;
    private javax.swing.JTextArea indieTA;
    private javax.swing.JTextArea indieTA1;
    private javax.swing.JPanel indieTab;
    private javax.swing.JButton indieTabBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel likedPage;
    private javax.swing.JTextArea likedTA;
    private javax.swing.JPanel likedTab;
    private javax.swing.JButton likedTabBtn;
    private javax.swing.JLabel musicLbl;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel playlistContainer;
    private javax.swing.JPanel repeatPage;
    private javax.swing.JPanel repeatTab;
    private javax.swing.JButton repeatTabBtn;
    private javax.swing.JPanel rockPage;
    private javax.swing.JRadioButton rockRBtn;
    private javax.swing.JPanel rockTab;
    private javax.swing.JButton rockTabBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField songTxtField;
    // End of variables declaration//GEN-END:variables
}
