/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author paulp
 */
public class MusicGUI extends javax.swing.JFrame {
    private StackInterface SI;
    private QueueInterface QIA;
    private QueueInterface QIB;
    /**
     * Creates new form MusicGUI
     */
    public MusicGUI() {
        initComponents();
        QIA = new GenreA();
        QIB = new GenreB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreGroup = new javax.swing.ButtonGroup();
        navBar = new javax.swing.JPanel();
        musicLbl = new javax.swing.JLabel();
        likedTab = new javax.swing.JPanel();
        likedTabBtn = new javax.swing.JButton();
        indieTab = new javax.swing.JPanel();
        indieTabBtn = new javax.swing.JButton();
        rockTab = new javax.swing.JPanel();
        rockTabBtn = new javax.swing.JButton();
        exit = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        playlistContainer = new javax.swing.JPanel();
        likedPage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        likedTA = new javax.swing.JTextArea();
        addGenBtn = new javax.swing.JButton();
        songTxtField = new javax.swing.JTextField();
        indieRBtn = new javax.swing.JRadioButton();
        rockRBtn = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        countLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        indiePage = new javax.swing.JPanel();
        iSearchBtn = new javax.swing.JButton();
        iCountLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        indieTA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        iDeleteBtn = new javax.swing.JButton();
        iClearBtn = new javax.swing.JButton();
        iSongTxtField = new javax.swing.JTextField();
        rockPage = new javax.swing.JPanel();
        rDeleteBtn = new javax.swing.JButton();
        rClearBtn = new javax.swing.JButton();
        rSongTxtField = new javax.swing.JTextField();
        rSearchBtn = new javax.swing.JButton();
        rCountLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rockTA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navBar.setBackground(new java.awt.Color(204, 153, 255));

        musicLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        musicLbl.setText("MUSIC PLAYLIST MANAGER");

        likedTabBtn.setBackground(new java.awt.Color(255, 204, 255));
        likedTabBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        likedTabBtn.setText("Liked");
        likedTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout likedTabLayout = new javax.swing.GroupLayout(likedTab);
        likedTab.setLayout(likedTabLayout);
        likedTabLayout.setHorizontalGroup(
            likedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(likedTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        likedTabLayout.setVerticalGroup(
            likedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(likedTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        indieTabBtn.setBackground(new java.awt.Color(255, 204, 255));
        indieTabBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        indieTabBtn.setText("Indie");
        indieTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indieTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indieTabLayout = new javax.swing.GroupLayout(indieTab);
        indieTab.setLayout(indieTabLayout);
        indieTabLayout.setHorizontalGroup(
            indieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indieTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        indieTabLayout.setVerticalGroup(
            indieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(indieTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rockTabBtn.setBackground(new java.awt.Color(255, 204, 255));
        rockTabBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rockTabBtn.setText("Rock");
        rockTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rockTabLayout = new javax.swing.GroupLayout(rockTab);
        rockTab.setLayout(rockTabLayout);
        rockTabLayout.setHorizontalGroup(
            rockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rockTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        rockTabLayout.setVerticalGroup(
            rockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rockTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        exitBtn.setBackground(new java.awt.Color(255, 204, 255));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitBtn.setText("X");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(navBarLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(musicLbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(navBarLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(likedTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(indieTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rockTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(musicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(likedTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indieTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rockTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        playlistContainer.setBackground(new java.awt.Color(204, 204, 204));
        playlistContainer.setLayout(new java.awt.CardLayout());

        likedPage.setBackground(new java.awt.Color(204, 153, 255));
        likedPage.setPreferredSize(new java.awt.Dimension(529, 355));

        likedTA.setColumns(20);
        likedTA.setRows(5);
        jScrollPane1.setViewportView(likedTA);

        addGenBtn.setText("Add to");
        addGenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGenBtnActionPerformed(evt);
            }
        });

        genreGroup.add(indieRBtn);
        indieRBtn.setText("Indie");

        genreGroup.add(rockRBtn);
        rockRBtn.setText("Rock");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        countLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        countLbl.setText("There are 0 songs in your playlist");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Liked Playlist");

        deleteBtn.setText("Remove");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout likedPageLayout = new javax.swing.GroupLayout(likedPage);
        likedPage.setLayout(likedPageLayout);
        likedPageLayout.setHorizontalGroup(
            likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likedPageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(likedPageLayout.createSequentialGroup()
                        .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(likedPageLayout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn))
                            .addComponent(countLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(likedPageLayout.createSequentialGroup()
                                .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(songTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(indieRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addGenBtn, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rockRBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(likedPageLayout.createSequentialGroup()
                        .addComponent(deleteBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, likedPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addContainerGap())
        );
        likedPageLayout.setVerticalGroup(
            likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likedPageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(likedPageLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(likedPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(songTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn)
                            .addComponent(searchBtn))
                        .addGap(18, 18, 18)
                        .addComponent(addGenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(indieRBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rockRBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn)
                        .addGap(12, 12, 12)
                        .addComponent(countLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addContainerGap())
        );

        playlistContainer.add(likedPage, "card2");

        indiePage.setBackground(new java.awt.Color(204, 153, 255));

        iSearchBtn.setText("Search");
        iSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSearchBtnActionPerformed(evt);
            }
        });

        iCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iCountLbl.setText("There are 0 songs in your playlist");

        indieTA.setColumns(20);
        indieTA.setRows(5);
        jScrollPane2.setViewportView(indieTA);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Indie Playlist");

        iDeleteBtn.setText("Remove");
        iDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iDeleteBtnActionPerformed(evt);
            }
        });

        iClearBtn.setText("Clear");
        iClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indiePageLayout = new javax.swing.GroupLayout(indiePage);
        indiePage.setLayout(indiePageLayout);
        indiePageLayout.setHorizontalGroup(
            indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiePageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indiePageLayout.createSequentialGroup()
                        .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(indiePageLayout.createSequentialGroup()
                                .addComponent(iSongTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iSearchBtn)))
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(iCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(indiePageLayout.createSequentialGroup()
                        .addComponent(iDeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iClearBtn)))
                .addContainerGap())
        );
        indiePageLayout.setVerticalGroup(
            indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indiePageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(indiePageLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iSongTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iSearchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(indiePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iDeleteBtn)
                            .addComponent(iClearBtn))
                        .addGap(12, 12, 12)
                        .addComponent(iCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        playlistContainer.add(indiePage, "card3");

        rockPage.setBackground(new java.awt.Color(204, 153, 255));

        rDeleteBtn.setText("Remove");
        rDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDeleteBtnActionPerformed(evt);
            }
        });

        rClearBtn.setText("Clear");
        rClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rClearBtnActionPerformed(evt);
            }
        });

        rSearchBtn.setText("Search");
        rSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSearchBtnActionPerformed(evt);
            }
        });

        rCountLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rCountLbl.setText("There are 0 songs in your playlist");

        rockTA.setColumns(20);
        rockTA.setRows(5);
        jScrollPane3.setViewportView(rockTA);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Rock Playlist");

        javax.swing.GroupLayout rockPageLayout = new javax.swing.GroupLayout(rockPage);
        rockPage.setLayout(rockPageLayout);
        rockPageLayout.setHorizontalGroup(
            rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockPageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rockPageLayout.createSequentialGroup()
                        .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rockPageLayout.createSequentialGroup()
                                .addComponent(rSongTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSearchBtn)))
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(rCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rockPageLayout.createSequentialGroup()
                        .addComponent(rDeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rClearBtn)))
                .addContainerGap())
        );
        rockPageLayout.setVerticalGroup(
            rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockPageLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rockPageLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSongTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSearchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rockPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rDeleteBtn)
                            .addComponent(rClearBtn))
                        .addGap(12, 12, 12)
                        .addComponent(rCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        playlistContainer.add(rockPage, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playlistContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playlistContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void likedTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedTabBtnActionPerformed
        // TODO add your handling code here:
        likedPage.setVisible(true);
        indiePage.setVisible(false);
        rockPage.setVisible(false);

    }//GEN-LAST:event_likedTabBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void indieTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indieTabBtnActionPerformed
        // TODO add your handling code here:
        likedPage.setVisible(false);
        indiePage.setVisible(true);
        rockPage.setVisible(false);
        
    }//GEN-LAST:event_indieTabBtnActionPerformed

    private void rockTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockTabBtnActionPerformed
        // TODO add your handling code here:
        likedPage.setVisible(false);
        indiePage.setVisible(false);
        rockPage.setVisible(true);
        
    }//GEN-LAST:event_rockTabBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Get the text entered in the songTxtField (presumably a text field for entering song titles)
        String title = songTxtField.getText();       

        // Push the title onto the stack
        SI.push(title);

        // Clear the likedTA text area
        likedTA.setText("");

        // Append the updated stack content to the likedTA text area
        likedTA.append(SI.displayStack() + "\n");

        // Get the number of songs in the stack
        int songNum = SI.size();

        // Update the countLbl label with the number of songs in the playlist
        countLbl.setText("There are " + songNum + " songs in your playlist\n");

        // Clear the songTxtField for the next entry
        songTxtField.setText("");

    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
            // Get the target element to search for
            String target = songTxtField.getText();
            // Search for the target element in the stack
            int index = SI.search(target);

            // Display the result
            if (index != -1) {
                likedTA.append("Song " + target + " found");
            } else {
                likedTA.append("Song " + target + " not found in the playlist");
            }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
            // Check if the stack (SI) is empty
            if (SI.isEmpty()) {
                // If the stack is empty, display a message indicating that there are no songs to be removed
                likedTA.append("There are no songs to be removed\n");
            } else {
                // If the stack is not empty, pop (remove) the top song from the stack
                SI.pop();

                // Clear the likedTA text area
                likedTA.setText("");

                // Append the updated stack content to the likedTA text area
                likedTA.append(SI.displayStack() + "\n");

                // Get the number of songs in the stack
                int songNum = SI.size();

                // Update the countLbl label with the number of songs in the playlist
                countLbl.setText("There are " + songNum + " songs in your playlist\n");
            }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
            // Empty the stack (SI)
            SI.emptyStack();

            // Get the number of songs in the stack after emptying it
            int songNum = SI.size();

            // Update the countLbl label with the number of songs in the playlist
            countLbl.setText("There are " + songNum + " songs in your playlist\n");

            // Clear the likedTA text area
            likedTA.setText("");

    }//GEN-LAST:event_clearBtnActionPerformed

    private void iSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSearchBtnActionPerformed
            // Get the target element to search for
            String target = iSongTxtField.getText();
            // Search for the target element in the stack
            boolean find = QIA.search(target);

            // Display the result
            if (find != false) {
                indieTA.append("Song " + target + " found");
            } else {
                indieTA.append("Song " + target + " not found in the playlist");
            }
    }//GEN-LAST:event_iSearchBtnActionPerformed

    private void iClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iClearBtnActionPerformed
            // Empty the queue (QIA)
            QIA.emptyQueue();

            // Get the number of songs in the queue after emptying it
            int songNum = QIA.size();

            // Update the iCountLbl label with the number of songs in the playlist after emptying it
            iCountLbl.setText("There are " + songNum + " songs in your playlist\n");

            // Clear the indieTA text area
            indieTA.setText("");

    }//GEN-LAST:event_iClearBtnActionPerformed

    private void iDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iDeleteBtnActionPerformed
            // Check if the queue QIA is not empty
            if (!QIA.isEmpty()) {
                // Dequeue the first song from the queue
                QIA.dequeue();

                // Clear the indieTA text area
                indieTA.setText(" ");

                // Display the remaining songs in the queue in the indieTA text area
                indieTA.append(QIA.displayQueue() + "\n");

                // Get the number of songs in the queue after removing one
                int iSongNum = QIA.size();

                // Update the iCountLbl label with the number of songs in the playlist
                iCountLbl.setText("There are " + iSongNum + " songs in your playlist\n");
            } else {
                // Display a message if there are no songs to be removed from the queue
                indieTA.append("There are no songs to be removed\n");
            }

    }//GEN-LAST:event_iDeleteBtnActionPerformed

    private void rDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDeleteBtnActionPerformed
        // Check if the rock playlist queue is not empty
        if (!QIB.isEmpty()) {
            // If the queue is not empty, dequeue the first song
            QIB.dequeue();

            // Clear the text area displaying the rock playlist
            rockTA.setText(" ");

            // Append the updated list of songs in the rock playlist to the text area
            rockTA.append(QIB.displayQueue() + "\n");

            // Get the number of songs remaining in the rock playlist queue
            int iSongNum = QIB.size();

            // Update the label displaying the number of songs in the rock playlist
            rCountLbl.setText("There are " + iSongNum + " songs in your playlist\n");
        } else {
            // If the queue is empty, display a message indicating there are no songs to be removed
            rockTA.append("There are no songs to be removed\n");
        }
    }//GEN-LAST:event_rDeleteBtnActionPerformed

    private void rClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rClearBtnActionPerformed
        // Empty the rock playlist queue
        QIB.emptyQueue();

        // Get the number of songs remaining in the rock playlist queue
        int songNum = QIB.size();

        // Update the label displaying the number of songs in the rock playlist
        rCountLbl.setText("There are " + songNum + " songs in your playlist\n");

        // Clear the text area displaying the rock playlist
        rockTA.setText("");
    }//GEN-LAST:event_rClearBtnActionPerformed

    private void rSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSearchBtnActionPerformed
        // Get the target element to search for from the text field
        String target = rSongTxtField.getText();

        // Search for the target element in the rock playlist queue
        boolean find = QIB.search(target);

        // Display the search result in the rock playlist text area
        if (find != false) {
            // If the target song is found, append a message indicating it was found
            rockTA.append("Song " + target + " found");
        } else {
            // If the target song is not found, append a message indicating it was not found
            rockTA.append("Song " + target + " not found in the playlist");
        }

    }//GEN-LAST:event_rSearchBtnActionPerformed

    private void addGenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGenBtnActionPerformed

        if(indieRBtn.isSelected()){      
            // Move the last song from the stack to the queue for indie genre
            Object moveSong = SI.pop(); // Pop the last song from the stack
            QIA.enqueue(moveSong); // Enqueue the song to the indie queue

            // Update the indie display area with the moved song
            indieTA.append(moveSong.toString() + "\n");

            // Update the liked playlist display area with the remaining songs in the stack
            likedTA.setText("");
            likedTA.append(SI.displayStack() + "\n");

            // Update the count label for the liked playlist
            int songNum = SI.size();
            countLbl.setText("There are " + songNum + " songs in your playlist\n");

            // Update the count label for the indie playlist
            int iSongNum = QIA.size();
            iCountLbl.setText("There are " + iSongNum + " songs in your playlist\n");
        }
        else if(rockRBtn.isSelected()){
            // Move the last song from the stack to the queue for rock genre
            Object moveSong = SI.pop(); // Pop the last song from the stack
            QIB.enqueue(moveSong); // Enqueue the song to the rock queue

            // Update the rock display area with the moved song
            rockTA.append(moveSong.toString() + "\n");

            // Update the liked playlist display area with the remaining songs in the stack
            likedTA.setText("");
            rockTA.append(SI.displayStack() + "\n");

            // Update the count label for the liked playlist
            int songNum = SI.size();
            countLbl.setText("There are " + songNum + " songs in your playlist\n");

            // Update the count label for the rock playlist
            int iSongNum = QIB.size();
            rCountLbl.setText("There are " + iSongNum + " songs in your playlist\n");
        }
        else{
            return; // Return if no genre is selected
        }

    }//GEN-LAST:event_addGenBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addGenBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel countLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel exit;
    private javax.swing.JButton exitBtn;
    private javax.swing.ButtonGroup genreGroup;
    private javax.swing.JButton iClearBtn;
    private javax.swing.JLabel iCountLbl;
    private javax.swing.JButton iDeleteBtn;
    private javax.swing.JButton iSearchBtn;
    private javax.swing.JTextField iSongTxtField;
    private javax.swing.JPanel indiePage;
    private javax.swing.JRadioButton indieRBtn;
    private javax.swing.JTextArea indieTA;
    private javax.swing.JPanel indieTab;
    private javax.swing.JButton indieTabBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel likedPage;
    private javax.swing.JTextArea likedTA;
    private javax.swing.JPanel likedTab;
    private javax.swing.JButton likedTabBtn;
    private javax.swing.JLabel musicLbl;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel playlistContainer;
    private javax.swing.JButton rClearBtn;
    private javax.swing.JLabel rCountLbl;
    private javax.swing.JButton rDeleteBtn;
    private javax.swing.JButton rSearchBtn;
    private javax.swing.JTextField rSongTxtField;
    private javax.swing.JPanel rockPage;
    private javax.swing.JRadioButton rockRBtn;
    private javax.swing.JTextArea rockTA;
    private javax.swing.JPanel rockTab;
    private javax.swing.JButton rockTabBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField songTxtField;
    // End of variables declaration//GEN-END:variables
}
